---
:concurrency: 10
staging:
  :concurrency: 10
production:
  :concurrency: 20
:queues:
  - critical
  - default
  - low

:schedule:
  ParseCsvBatchJob:
    cron: '0 1 * * 1 America/Los_Angeles'
    class: ParseCsvBatchJob
  IpAddressRangeImportJob:
    cron: '0 1 * * 2 America/Los_Angeles'
    class: IpAddressRangeImportJob
