---
:concurrency: 10
staging:
  :concurrency: 10
production:
  :concurrency: 20
:queues:
  - critical
  - default
  - low

:schedule:
  parse_csv_batch_job:
    cron: '0 1 * * 1 America/Los_Angeles'
    class: ParseCsvBatchJob
  ip_address_range_import_job:
    cron: '0 1 * * 2 America/Los_Angeles'
    class: IpAddressRangeImportJob
