---
:concurrency: 10
staging:
  :concurrency: 10
production:
  :concurrency: 20
:queues:
  - critical
  - default
  - low

:schedule:
  ParseCsvBatchJob:
    # Runs at 1am on the first of every month
    cron: '0 1 1 * * America/Los_Angeles'
    class: ParseCsvBatchJob
  IpAddressRangeImportJob:
    # Runs at 1am on the second of every month
    cron: '0 1 2 * * America/Los_Angeles'
    class: IpAddressRangeImportJob
