---
:concurrency: 10
staging:
  :concurrency: 10
production:
  :concurrency: 20
:queues:
  - critical
  - default
  - low

:schedule:
  CleanUpRequestsBatchJob:
    # Runs at 5am Everyday
    cron: '0 2 15 * * America/Los_Angeles'
    class: CleanUpRequestsBatchJob
  IpAddressRangeImportJob:
    # Runs at 2am on the 2nd of every month
    cron: '0 2 2 * * America/Los_Angeles'
    class: IpAddressRangeImportJob
  ParseCsvBatchJob:
    # Runs at 11pm on the 1st of every month
    cron: '0 23 1 * * America/Los_Angeles'
    class: ParseCsvBatchJob
